#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Script to start the demo API 
"""

from flask import Flask, request, jsonify
import json

app = Flask(__name__)

@app.route('/data', methods=['POST'])
def receive_data():
    if not request.is_json:
        return jsonify({'error': 'Expected JSON'}), 400
    data = request.get_json()
    # Save the received JSON result
    with open('/home/dgrossen/result.json', 'w') as rfile:
        json.dump(data, rfile)
    #print(f"Received {data=}")
    return jsonify({'status': 'success'}), 200

if __name__ == '__main__':
    #app.run(host='0.0.0.0', port=4711, ssl_context='adhoc')  # HTTPS with autogenerated cert
    app.run(host='0.0.0.0', port=4711) #http://172.17.0.1:4711/data